### ISSUE TITLE
  ServerlessError: 400 

### ISSUE THREAD

**Issue by rathoregee** [localstack/serverless-localstack#262] opened 2024-07-30 22:31 UTC
Package.json
 "devDependencies": {
    "serverless": "^2.72.4",
    "serverless-localstack": "^1.2.1"
  } 

-----------------------------------------------
```
service: serverless-localstack-graphql

#frameworkVersion: "3"
# Enable localstack plugin
plugins:
  - serverless-localstack
# Configure localstack plugin
custom:
  localstack:
    # Only use localstack for the local stage
    stages:
      - local
    host: http://localhost  # optional - LocalStack host to connect to
    edgePort: 4566  # optional - LocalStack edge port to connect to
    # Setup a docker volume for localstack to run code from to improve performance
    lambda:
      mountCode: true
    # Startup localstack automatically
    autostart: true
    debug: true
    networks: #optional - attaches the list of networks to the localstack docker container after startup
      - host
      - mynetwork
provider:
  name: aws
  stage: ${opt:stage, self:custom.defaultStage}
  runtime: nodejs18.x
  lambdaHashingVersion: '20201221'

functions:
  hello:
    events:
      - http:
          # integration: lambda
          method: get
          path: hello
    handler: handler.hello

```

-----------------------------------------------
ERROR

```
 ServerlessError: 400
      at Request.extractError (C:\GraphQL\serverless-localstack-dokcompose\node_modules\aws-sdk\lib\protocol\query.js:50:29)
      at Request.callListeners (C:\GraphQL\serverless-localstack-dokcompose\node_modules\aws-sdk\lib\sequential_executor.js:106:20)
      at Request.emit (C:\GraphQL\serverless-localstack-dokcompose\node_modules\aws-sdk\lib\sequential_executor.js:78:10)
      at Request.emit (C:\GraphQL\serverless-localstack-dokcompose\node_modules\aws-sdk\lib\request.js:686:14)
      at Request.transition (C:\GraphQL\serverless-localstack-dokcompose\node_modules\aws-sdk\lib\request.js:22:10)
      at AcceptorStateMachine.runTo (C:\GraphQL\serverless-localstack-dokcompose\node_modules\aws-sdk\lib\state_machine.js:14:12)
      at C:\GraphQL\serverless-localstack-dokcompose\node_modules\aws-sdk\lib\state_machine.js:26:10
      at Request.<anonymous> (C:\GraphQL\serverless-localstack-dokcompose\node_modules\aws-sdk\lib\request.js:38:9)
      at Request.<anonymous> (C:\GraphQL\serverless-localstack-dokcompose\node_modules\aws-sdk\lib\request.js:688:12)
      at Request.callListeners (C:\GraphQL\serverless-localstack-dokcompose\node_modules\aws-sdk\lib\sequential_executor.js:116:18)
      at Request.emit (C:\GraphQL\serverless-localstack-dokcompose\node_modules\aws-sdk\lib\sequential_executor.js:78:10)
      at Request.emit (C:\GraphQL\serverless-localstack-dokcompose\node_modules\aws-sdk\lib\request.js:686:14)
      at Request.transition (C:\GraphQL\serverless-localstack-dokcompose\node_modules\aws-sdk\lib\request.js:22:10)
      at AcceptorStateMachine.runTo (C:\GraphQL\serverless-localstack-dokcompose\node_modules\aws-sdk\lib\state_machine.js:14:12)
      at C:\GraphQL\serverless-localstack-dokcompose\node_modules\aws-sdk\lib\state_machine.js:26:10
      at Request.<anonymous> (C:\GraphQL\serverless-localstack-dokcompose\node_modules\aws-sdk\lib\request.js:38:9)
      at Request.<anonymous> (C:\GraphQL\serverless-localstack-dokcompose\node_modules\aws-sdk\lib\request.js:688:12)
      at Request.callListeners (C:\GraphQL\serverless-localstack-dokcompose\node_modules\aws-sdk\lib\sequential_executor.js:116:18)
      at callNextListener (C:\GraphQL\serverless-localstack-dokcompose\node_modules\aws-sdk\lib\sequential_executor.js:96:12)
      at IncomingMessage.onEnd (C:\GraphQL\serverless-localstack-dokcompose\node_modules\aws-sdk\lib\event_listeners.js:417:13)
      at IncomingMessage.emit (node:events:529:35)
      at IncomingMessage.emit (node:domain:489:12)
      at endReadableNT (node:internal/streams/readable:1400:12)
      at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
  ----------------------------------------------------------------------------------------------------
      at C:\GraphQL\serverless-localstack-dokcompose\node_modules\serverless\lib\aws\request.js:226:11
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async persistentRequest (C:\GraphQL\serverless-localstack-dokcompose\node_modules\serverless\lib\aws\request.js:150:14)
```

**Comment by steffyP** [comment] 2024-08-29 12:07
Hi @rathoregee, 

could you please provide more information, e.g. the handler-code, and please also share the entire logs from localstack, preferably with `DEBUG=1` enabled. Thank you!

**Comment by steffyP** [comment] 2024-09-24 08:01
Hi @rathoregee,
we haven't heard back from you yet. If you can't provide the information we asked for, we will have to close the ticket due to inactivity and not being able to reproduce it with the information given.

**Comment by steffyP** [comment] 2024-09-30 12:25
Hi @rathoregee,
we haven't received any response from you within a month. As with the information provided we are not able to reproduce the issue, we are now closing the ticket.

If you still encounter the issue, and can provide the requested information, please feel free to re-open the ticket.

**Closed by steffyP** 2024-09-30 12:25 UTC
Labels: status: response required
