### ISSUE TITLE
Is this plugin supposed to work on the latest Serverless version?

### ISSUE THREAD

**Issue by rdsedmundo** [localstack/serverless-localstack#80] opened 2020-03-10 13:08 UTC
I downloaded the `localstack` and this plugin to give it a try, tried to make it work for 2h, but it simply won't work. A lot of random errors keep happening. The health check is showing that all services are running perfectly, so I either assume that there's an incompatibility with the latest `serverless` framework version, or the README instructions are insufficient.

My config:
```yml
service: serverless-blank

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1

plugins:
  - serverless-localstack

custom:
  localstack:
    debug: true
    stages:
      - local
    host: http://localhost
    # tried with and without the following enabled
    # lambda:
    #   mountCode: true

functions:
  hello:
    handler: src/handler.hello
```

I tried to set up both with an ongoing project and one built from scratch (the Hello World template above), none worked.

Below there are some errors I faced, some of them were because I was using `custom.localstack.lambda.mountCode`, so I disabled it, but then another ones appeared, e.g bucket doesn't exist, so I tried to create the buckets manually using the `awslocal` CLI, but then it threw an error saying that the function already existed during the deployment—I also tried got riding of everything and creating the stack and the service once again, but in the first deployment it already throws that the function already exists.

```
20-03-10T12:05:31:DEBUG:localstack.services.cloudformation.cloudformation_listener: Error response from CloudFormation (404) POST /: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error>\n    <Code>NoSuchBucket</Code>\n    <Message>The specified bucket does not exist</Message>\n    <BucketName>todo-local-ServerlessDeploymentBucket-VXACEBLRD0M8</BucketName>\n    <RequestID>7a62c49f-347e-4fc4-9331-6e8eEXAMPLE</RequestID>\n</Error>'
```
```
moto.awslambda.exceptions.InvalidParameterValueException: An error occurred (InvalidParameterValueException) when calling the None operation: Error occurred while GetObject. S3 Error Code: NoSuchBucket. S3 Error Message: The specified bucket does not exist

<Error>
    <Code>NoSuchBucket</Code>
    <Message>The specified bucket does not exist</Message>
    <BucketName>__local__</BucketName>
    <RequestID>7a62c49f-347e-4fc4-9331-6e8eEXAMPLE</RequestID>
</Error>
```

```
botocore.errorfactory.ResourceConflictException: An error occurred (ResourceConflictException) when calling the CreateFunction operation: Function already exist: serverless-blank-local-graphql
```

```
  Serverless Error ---------------------------------------

  ServerlessError: The specified bucket does not exist
      at /Users/rdsedmundo/serverless-blank/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:329:27
      at processTicksAndRejections (internal/process/task_queues.js:94:5)
```

**Comment by yannbr** [comment] 2020-03-10 18:24
I got this issue as well, but after waiting ~1min after booting up localstack, the deployment passed that error. (I'm actually stuck on another error)

**Comment by whummer** [comment] 2020-03-15 02:42
Thanks for reporting @rdsedmundo . We've recently made some improvements to the CloudFormation API - can you please do a `docker pull localstack/localstack` and give it a try with the latest version? Thanks

**Comment by larrybolt** [comment] 2020-03-28 00:53
Same issues is still happening, I'm using this serverless.yml:
```yml
service: simple-lambda-test
plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-localstack
provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1
  logRetentionInDays: 3
  stage: dev
  versionFunctions: false
  environment:
    ENV_VAR_INSIDE_LAMBDA: ${self:custom.envVar}
package:
  exclude:
    - node_modules/**

functions:
  hello:
    handler: hello.handler
    events:
      - http: GET /
          
custom:
  envVar: ${env:ENV_VAR_WHEN_RUNNING_SLS,"default-value"}
  localstack:
    stages: 
      - local
    host: http://nuc
  serverless-offline:
    port: 4000
```
Log I get from localstack is:
```
localstack_main | 2020-03-28T00:43:46:DEBUG:localstack.services.cloudformation.cloudformation_listener: Error response for CloudFormation action "DescribeStacks" (400) POST /: b'<ErrorResponse xmlns="http://cloudformation.amazonaws.com/doc/2010-05-15/">\n  <Error>\n    <Type>Sender</Type>\n    <Code>ValidationError</Code>\n    <Message>Stack with id simple-lambda-test-local does not exist</Message>\n  </Error>\n  <RequestId>cf4c737e-5ae2-11e4-a7c9-ad44eEXAMPLE</RequestId>\n</ErrorResponse>'
localstack_main | 2020-03-28T00:43:46:DEBUG:localstack.services.cloudformation.cloudformation_starter: Currently processing stack resource simple-lambda-test-local/ServerlessDeploymentBucket: None
localstack_main | 2020-03-28T00:43:46:ERROR:localstack.services.cloudformation.cloudformation_starter: Unable to parse and create resource "ServerlessDeploymentBucket": 400 Bad Request: <?xml version="1.0" encoding="UTF-8"?>
localstack_main | <Error>
localstack_main |     <Code>InvalidBucketName</Code>
localstack_main |     <Message>The specified bucket is not valid.</Message>
localstack_main |     
localstack_main |     <RequestID>7a62c49f-347e-4fc4-9331-6e8eEXAMPLE</RequestID>
localstack_main | </Error> Traceback (most recent call last):
localstack_main |   File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_starter.py", line 175, in parse_and_create_resource
localstack_main |     return _parse_and_create_resource(
localstack_main |   File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_starter.py", line 243, in _parse_and_create_resource
localstack_main |     raise moto_create_error
localstack_main |   File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_starter.py", line 228, in _parse_and_create_resource
localstack_main |     resource = parse_and_create_resource_orig(
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/cloudformation/parsing.py", line 343, in parse_and_create_resource
localstack_main |     resource = resource_class.create_from_cloudformation_json(
localstack_main |   File "/opt/code/localstack/localstack/services/s3/s3_starter.py", line 84, in Bucket_create_from_cloudformation_json
localstack_main |     result = create_from_cloudformation_json_orig(resource_name, cloudformation_json, region_name)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/s3/models.py", line 1096, in create_from_cloudformation_json
localstack_main |     bucket = s3_backend.create_bucket(resource_name, region_name)
localstack_main |   File "/opt/code/localstack/localstack/services/s3/s3_starter.py", line 96, in create_bucket
localstack_main |     return create_bucket_orig(bucket_name, region_name, *args, **kwargs)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/s3/models.py", line 1189, in create_bucket
localstack_main |     raise InvalidBucketName()
localstack_main | moto.s3.exceptions.InvalidBucketName: 400 Bad Request: <?xml version="1.0" encoding="UTF-8"?>
localstack_main | <Error>
localstack_main |     <Code>InvalidBucketName</Code>
localstack_main |     <Message>The specified bucket is not valid.</Message>
localstack_main |     
localstack_main |     <RequestID>7a62c49f-347e-4fc4-9331-6e8eEXAMPLE</RequestID>
localstack_main | </Error>
localstack_main | 
localstack_main | 2020-03-28T00:43:46:DEBUG:localstack.services.cloudformation.cloudformation_listener: Error response for CloudFormation action "CreateStack" (400) POST /: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error>\n    <Code>InvalidBucketName</Code>\n    <Message>The specified bucket is not valid.</Message>\n    \n    <RequestID>7a62c49f-347e-4fc4-9331-6e8eEXAMPLE</RequestID>\n</Error>'
```
And here are the cf stacks: 
https://gist.github.com/larrybolt/5b8ad2644e1d04c34b02f848c3c88572

And here's a demo repo you can try yourself:
https://github.com/catsies-dev/serverless-apigateway-typescript-lambda

**Comment by gschaetz** [comment] 2020-03-28 05:09
I got this to work if you pull localstack/localstack:0.10.8 with the most recent version of serverless and serverless-localstack

**Comment by whummer** [comment] 2020-03-29 21:59
Thanks @gschaetz @larrybolt @rdsedmundo - looks like a duplicate of #84 . This should be fixed in https://github.com/localstack/localstack/pull/2220, can you please give it another try with the `latest` version of the Docker image? Please report here if the problem persists. Thanks

**Closed by whummer** 2020-03-29 21:59 UTC

**Comment by larrybolt** [comment] 2020-04-03 03:10
@whummer I'm still getting next error:
```
localstack_1  | Waiting for all LocalStack services to be ready
localstack_1  | 2020-04-03 03:06:37,867 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
localstack_1  | 2020-04-03 03:06:37,870 INFO supervisord started with pid 13
localstack_1  | 2020-04-03 03:06:38,872 INFO spawned: 'dashboard' with pid 19
localstack_1  | 2020-04-03 03:06:38,875 INFO spawned: 'infra' with pid 20
localstack_1  | 2020-04-03 03:06:38,883 INFO success: dashboard entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
localstack_1  | (. .venv/bin/activate; bin/localstack web)
localstack_1  | (. .venv/bin/activate; exec bin/localstack start --host)
localstack_1  | Starting local dev environment. CTRL-C to quit.
localstack_1  | 2020-04-03 03:06:40,568 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
localstack_1  | Waiting for all LocalStack services to be ready
localstack_1  | Starting mock API Gateway (http port 4567)...
localstack_1  | 2020-04-03T03:06:46:INFO:localstack.multiserver: Starting multi API server process on port 51492
localstack_1  | Starting mock CloudFormation (http port 4581)...
localstack_1  | Starting mock DynamoDB (http port 4569)...
localstack_1  | Starting mock DynamoDB Streams service (http port 4570)...
localstack_1  | Starting mock Kinesis (http port 4568)...
localstack_1  | Starting mock Lambda service (http port 4574)...
localstack_1  | Starting mock CloudWatch Logs (http port 4586)...
localstack_1  | Starting mock S3 (http port 4572)...
localstack_1  | Starting mock SNS (http port 4575)...
localstack_1  | Starting mock SQS (http port 4576)...
localstack_1  | Listening at http://:::4565
localstack_1  | Initializing DynamoDB Local with the following configuration:
localstack_1  | Port:	4564
localstack_1  | InMemory:	false
localstack_1  | DbPath:	/tmp/localstack/data/dynamodb
localstack_1  | SharedDb:	true
localstack_1  | shouldDelayTransientStatuses:	false
localstack_1  | CorsParams:	*
localstack_1  | 
localstack_1  | 2020-04-03 03:06:48,002:API:  * Running on http://0.0.0.0:4566/ (Press CTRL+C to quit)
localstack_1  | 2020-04-03 03:06:48,002:API:  * Running on http://0.0.0.0:4566/ (Press CTRL+C to quit)
localstack_1  | 2020-04-03 03:06:48,002:API:  * Running on http://0.0.0.0:4566/ (Press CTRL+C to quit)
localstack_1  | 2020-04-03 03:06:48,058:API:  * Running on http://0.0.0.0:4559/ (Press CTRL+C to quit)
localstack_1  | 2020-04-03 03:06:48,058:API:  * Running on http://0.0.0.0:4559/ (Press CTRL+C to quit)
localstack_1  | 2020-04-03 03:06:48,058:API:  * Running on http://0.0.0.0:4559/ (Press CTRL+C to quit)
localstack_1  | 03:06:49.597 [main] INFO  org.elasticmq.server.Main$ - Starting ElasticMQ server (0.15.5) ...
localstack_1  | 03:06:50.642 [elasticmq-akka.actor.default-dispatcher-6] INFO  akka.event.slf4j.Slf4jLogger - Slf4jLogger started
localstack_1  | Waiting for all LocalStack services to be ready
localstack_1  | 03:06:52.102 [elasticmq-akka.actor.default-dispatcher-6] INFO  o.e.rest.sqs.TheSQSRestServerBuilder - Started SQS rest server, bind address 0.0.0.0:4561, visible server address http://6ae2b87fe832:4576
localstack_1  | 03:06:52.103 [main] INFO  org.elasticmq.server.Main$ - === ElasticMQ server (0.15.5) started in 3688 ms ===
localstack_1  | Ready.
localstack_1  | 2020-04-03T03:06:54:INFO:localstack.utils.persistence: Restored 1 API calls from persistent file: /tmp/localstack/data/recorded_api_calls.json
localstack_1  | 2020-04-03T03:07:20:DEBUG:localstack.services.cloudformation.cloudformation_listener: Error response for CloudFormation action "DescribeStacks" (400) POST /: b'<ErrorResponse xmlns="http://cloudformation.amazonaws.com/doc/2010-05-15/">\n  <Error>\n    <Type>Sender</Type>\n    <Code>ValidationError</Code>\n    <Message>Stack with id simplelambdatest-local does not exist</Message>\n  </Error>\n  <RequestId>cf4c737e-5ae2-11e4-a7c9-ad44eEXAMPLE</RequestId>\n</ErrorResponse>'
localstack_1  | 2020-04-03T03:07:20:DEBUG:localstack.services.cloudformation.cloudformation_starter: Currently processing stack resource simplelambdatest-local/ServerlessDeploymentBucket: None
localstack_1  | 2020-04-03T03:07:20:DEBUG:localstack.services.cloudformation.cloudformation_starter: Deploying CloudFormation resource (update=False, exists=False, updateable=False): {'Type': 'AWS::S3::Bucket', 'Properties': {'BucketEncryption': {'ServerSideEncryptionConfiguration': [{'ServerSideEncryptionByDefault': {'SSEAlgorithm': 'AES256'}}]}, 'BucketName': 'simplelambdatest-local-ServerlessDeploymentBucket-UN52OATRGS4L'}}
localstack_1  | 2020-04-03T03:07:20:DEBUG:localstack.utils.cloudformation.template_deployer: Running action "create" for resource type "S3::Bucket" id "ServerlessDeploymentBucket"
localstack_1  | 2020-04-03T03:07:20:DEBUG:localstack.utils.cloudformation.template_deployer: Request for resource type "S3::Bucket" in region us-east-1: create_bucket {'Bucket': 'simplelambdatest-local-ServerlessDeploymentBucket-UN52OATRGS4L', 'ACL': 'public-read', 'CreateBucketConfiguration': {'LocationConstraint': 'us-east-1'}}
localstack_1  | 2020-04-03T03:07:20:DEBUG:localstack.services.cloudformation.cloudformation_starter: Currently processing stack resource simplelambdatest-local/ServerlessDeploymentBucketPolicy: None
localstack_1  | 2020-04-03T03:07:20:WARNING:moto: No Moto CloudFormation support for AWS::S3::BucketPolicy
localstack_1  | 2020-04-03T03:07:20:DEBUG:localstack.services.cloudformation.cloudformation_starter: Running CloudFormation stack deployment loop iteration 1
localstack_1  | 2020-04-03T03:07:25:WARNING:localstack.services.awslambda.lambda_api: Function not found: arn:aws:lambda:us-east-1:000000000000:function:simplelambdatest-local-hello
```
What would be the next steps for me to debug this?

**Comment by EthanSK** [comment] 2020-04-14 19:58
I'm still getting this error too

**Comment by maxgr0** [comment] 2020-05-29 16:20
Getting the same combination of errors using latest localstack version and the latest version of serverless-localstack
