### ISSUE TITLE
I Can’t get supersecret variables

### ISSUE THREAD

**Issue by danielcastill0** [localstack/serverless-localstack#106] opened 2020-09-08 03:11 UTC
Hey guys I’m trying to put into my lambda function environment variables from SSM but I got something like “could be found the resource ...” when I did deploy. I already created my own secrets manager in localstack
But they aren’t recognized in my Serverless project. Can anyone help me?

**Comment by josephnle** [comment] 2020-10-08 22:40
I think I'm also having an issue similar to this.

My project has a collection of serverless projects to split up the stack. I rely on CloudFormation outputs and SSM to share variables between the modules. It seems that I'm not able to reference outputs on locally created stacks.

For example, stack A:
```
service: notifications

plugins:
  - serverless-localstack

provider:
  name: aws
  runtime: nodejs10.x
  region: us-east-1
  stage: ${opt:stage, 'local'}

custom:
  localstack:
    stages:
      - local
    autostart: true

resources:
  Resources:
    ArtifactChanges:
      Type: AWS::SNS::Topic

  Outputs:
    ArtifactChanges:
      Value: !Ref ArtifactChanges
```

Referenced in stack B:

```
service: api

plugins:
  - serverless-localstack

provider:
  name: aws
  runtime: nodejs10.x
  region: us-east-1
  stage: ${opt:stage, 'local'}
  profile: localstack
  environment:
    ARTIFACT_TOPIC: ${cf:notifications-${self:provider.stage}.ArtifactChanges}
```

Throws error:
```
Stack with id notifications-local does not exist
```

Is serverless-localstack not able to intercept the fetching of the SSM and CF output variables?

**Comment by whummer** [comment] 2020-10-11 08:58
Thanks for reporting @danielcastill0 . Can you please share a small example to help us reproduce this issue? Generally speaking, referencing SSM parameters in your Serverless config should work - please make sure that the LocalStack region (via `DEFAULT_REGION`) matches the region of your sls stack. Thanks

Thanks for reporting @josephnle . Looks like your stack B may be talking to actual AWS, instead of LocalStack? I was actually able to get your example deployed by adding this section to serverless.yml for stack B:
```
custom:
  localstack:
    stages:
      - local
```

**Comment by josephnle** [comment] 2020-10-16 17:54
@whummer Sorry, I actually did have the `custom` config block but forgot to put it in the example. If I remove the environment variables, it deploys successfully. You're right in the fact that it does look like serverless-localstack isn't running early enough to prevent my stack from attempting to fetch the variable from AWS.

I've put this reproduction into a repo: https://github.com/josephnle/sls-localstack-test

Also let me know if this problem requires a separate GitHub issue - would be happy to create a new one if necessary.

**Comment by whummer** [comment] 2020-10-25 12:24
Thanks for the update @josephnle . We recently pushed a new release with some fixes related to resolving of variables - can you please give it another try using `serverless-localstack` version `0.4.28` or higher? Thanks for your help.

**Closed** 2020-10-25 12:25 UTC
Labels: configuration, needs-triaging
