### ISSUE TITLE
Unable to use external YAML files to configure plugin

### ISSUE THREAD

**Issue by scrofungulus** [localstack/serverless-localstack#88] opened 2020-04-22 19:20 UTC
WIth the following configuration: 

```
plugins: 
  - serverless-localstack
custom: 
  localstack: ${file(../../localstack.yml):localstack}
```

The plugin does not get configured properly and ends up just using plugin's default configuration.

If I do a `serverless print` the output is as expected with the proper configuration:

```
plugins:
  - serverless-localstack
custom:
  localstack:
    stages:
      - local
    autostart: true
    endpoints: null
    lambda:
      mountCode: false
    docker:
      sudo: false
    debug: true
```

My use case is that I am maintaining a monorepo of Lambda functions and would desire to not replicate configuration across each function. Another note, as I know that this has lifecycle considerations as well, is that I am using SSM parameters in my `provider` block. 

Is this desired, if not is it feasible to support this?

┆Issue is synchronized with this [Jira Task](https://localstack.atlassian.net/browse/LOC-34) by [Unito](https://www.unito.io/learn-more)

**Comment by monty16597** [comment] 2020-08-24 18:48
@scrofungulus  **Thank you for reporting this issue.**
Can you please give it a try once again using latest release? We tried according your use-case, but we are not able to reproduce the issue. I think the issue has already been resolved in the latest release. If you are still facing the same issue in latest release and if you can provide us code or both (serverless.yml and localstack.yml) files,then it will be helpful for us to reproducing the issue. **Thank you.**

**Closed** 2022-10-13 18:44 UTC
