### ISSUE TITLE
Deployment can break when trying to resolve role dependencies

### ISSUE THREAD

**Issue by phil-f** [localstack/serverless-localstack#96] opened 2020-07-19 22:57 UTC
Currently the following yml errors when deploying to localstack:

**Example**

```
service: example
frameworkVersion: '>=1.28.0 <2.0.0'
package:
  individually: true
  exclude:
    - ../../**

provider:
  name: aws
  runtime: go1.x
  region: us-east-1
  stage: local
  memorySize: 128

custom:
  localstack:
    debug: true
    host: http://localhost
    stages:
      - local

stepFunctions:
  stateMachines:
    exampleStateMachine:
      id: ExampleStateMachine
      name: exampleStateMachine
      definition:
        StartAt: TestRun
        States:
          TestRun:
            Type: Pass
            End: true

resources:
  Resources:
    exampleRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: exampleRole
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: examplePolicy
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - logs:CreateLogStream
                    - logs:CreateLogGroup
                    - logs:PutLogEvents
                  Resource:
                    - 'Fn::Join':
                      - ':'
                      -
                        - 'arn:aws:logs'
                        - Ref: 'AWS::Region'
                        - Ref: 'AWS::AccountId'
                        - 'log-group:/aws/lambda/${self:functions.exampleFunction.name}:*:*'
                - Effect: "Allow"
                  Action:
                    - "states:*"
                  Resource:
                    Ref: ExampleStateMachine

functions:
  exampleFunction:
    name: exampleFunction
    role: exampleRole
    handler: bin/exampleFunction/main
    package:
      include:
        - ../../bin/exampleFunction/main

plugins:
  - serverless-localstack
  - serverless-step-functions
```

**Error output:**

```
localstack_main | 2020-07-19T21:55:39:WARNING:localstack.services.cloudformation.cloudformation_starter: Unable to determine physical_resource_id for resource <class 'localstack.services.cloudformation.service_models.S3BucketPolicy'>
localstack_main | 2020-07-19T21:55:40:WARNING:localstack.services.awslambda.lambda_api: Function not found: arn:aws:lambda:us-east-1:000000000000:function:exampleFunction
localstack_main | 2020-07-19T21:55:41:INFO:localstack.services.cloudformation.cloudformation_starter: Resource ExampleStateMachine cannot be deployed, found unsatisfied dependencies. {'Type': 'AWS::StepFunctions::StateMachine', 'Properties': {'DefinitionString': '{\n  "StartAt": "TestRun",\n  "States": {\n    "TestRun": {\n      "Type": "Pass",\n      "End": true\n    }\n  }\n}', 'RoleArn': 'arn:aws:iam::000000000000:role/example-local-ExampleStateMachineRole-EF2SW2JV24OX', 'StateMachineName': 'exampleStateMachine'}, 'DependsOn': ['ExampleStateMachineRole']}
localstack_main | 2020-07-19T21:55:41:WARNING:localstack.services.cloudformation.cloudformation_starter: Unable to find ARN, using "name" instead: {'Ref': 'ExampleStateMachine'} - <localstack.stepfunctions.models.StateMachine object at 0x7f7161746040>
localstack_main | 2020-07-19T21:55:42:WARNING:localstack.services.awslambda.lambda_api: Function not found: arn:aws:lambda:us-east-1:000000000000:function:exampleFunction
localstack_main | 2020-07-19T21:55:42:WARNING:localstack.services.cloudformation.cloudformation_starter: Unable to find ARN, using "name" instead: {'Ref': 'ExampleStateMachine'} - <localstack.stepfunctions.models.StateMachine object at 0x7f7161746040>
localstack_main | 2020-07-19T21:55:42:INFO:localstack.services.cloudformation.cloudformation_starter: Resource ExampleStateMachine cannot be deployed, found unsatisfied dependencies. {'Type': 'AWS::StepFunctions::StateMachine', 'Properties': {'DefinitionString': '{\n  "StartAt": "TestRun",\n  "States": {\n    "TestRun": {\n      "Type": "Pass",\n      "End": true\n    }\n  }\n}', 'RoleArn': 'arn:aws:iam::000000000000:role/example-local-ExampleStateMachineRole-EF2SW2JV24OX', 'StateMachineName': 'exampleStateMachine'}, 'DependsOn': ['ExampleStateMachineRole']}
localstack_main | 2020-07-19T21:55:42:WARNING:localstack.services.cloudformation.cloudformation_starter: Unresolvable dependencies, there may be undeployed stack resources: {'ExampleStateMachine': ['ExampleStateMachine', {'Type': 'AWS::StepFunctions::StateMachine', 'Properties': {'DefinitionString': '{\n  "StartAt": "TestRun",\n  "States": {\n    "TestRun": {\n      "Type": "Pass",\n      "End": true\n    }\n  }\n}', 'RoleArn': 'arn:aws:iam::000000000000:role/example-local-ExampleStateMachineRole-EF2SW2JV24OX', 'StateMachineName': 'exampleStateMachine'}, 'DependsOn': ['ExampleStateMachineRole']}, <moto.cloudformation.parsing.ResourceMap object at 0x7f71627d4700>, 'us-east-1']}
localstack_main | 2020-07-19T21:55:42:WARNING:bootstrap.py: Thread run method <function apply_patches.<locals>.run_dependencies_deployment_loop.<locals>.run_loop at 0x7f7161bff700>(None) failed: Traceback (most recent call last):
localstack_main |   File "/opt/code/localstack/localstack/utils/bootstrap.py", line 499, in run
localstack_main |     self.func(self.params)
localstack_main |   File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_starter.py", line 843, in run_loop
localstack_main |     raise Exception('Unable to resolve all CloudFormation resources after traversing ' +
localstack_main | Exception: Unable to resolve all CloudFormation resources after traversing dependency tree (maximum depth 40 reached): ['ExampleStateMachine']
```

It's saying that the state machine can't be deployed because the role which it depends on can't be resolved.

What's also strange is that if you modify the yml above to refer to an existing bucket, e.g. add the following to the provider block:

```
 deploymentBucket:
  name: examplebucket
```

and then make sure the bucket exists on localstack before deploying, the error goes away and it works fine.

Any idea what could be going on here?

**Env Info**

```
Localstack v0.11.3
Serverless:
  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              12.18.2
     Framework Version:         1.74.1
     Plugin Version:            3.6.15
     SDK Version:               2.3.1
     Components Version:        2.31.12
```

**Comment by monty16597** [comment] 2020-09-18 17:27
@phil-f  Thank you for reporting the issue. I have tried and not able to reproduce it It might be possible that it has already been resolved.  Can you please give it a try with the latest release or using latest docker image ? Thank You.

**Comment by whummer** [comment] 2020-10-01 19:31
Thanks for reporting @phil-f . Closing this issue as "cannot-reproduce" - please report here with steps to reproduce if the problem persists with the `latest` version. Thanks!

**Closed by whummer** 2020-10-01 19:31 UTC
Labels: cannot-reproduce

**Comment by chriszirkel** [comment] 2020-12-21 15:16
I have a similar issue and I guess it has to do with StepFunctions state machine. 

```
raise error_class(parsed_response, operation_name)

botocore.errorfactory.ResourceConflictException: An error occurred (ResourceConflictException) when calling the CreateFunction operation: Function already exist: nebula-shopify-local-transformData


2020-12-21T15:06:06:INFO:localstack.services.cloudformation.cloudformation_starter: Error running stack deployment loop: An error occurred (ResourceConflictException) when calling the CreateFunction operation: Function already exist: nebula-shopify-local-transformData

2020-12-21T15:06:06:WARNING:bootstrap.py: Thread run method <function apply_patches.<locals>.run_dependencies_deployment_loop.<locals>.run_loop at 0x7ffa4f95ff70>(None) failed: Unable to resolve all CloudFormation resources after traversing dependency tree (maximum depth 40): [] Traceback (most recent call last):

File "/opt/code/localstack/localstack/utils/bootstrap.py", line 581, in run

result = self.func(self.params)

File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_starter.py", line 1217, in run_loop

raise Exception('Unable to resolve all CloudFormation resources after traversing ' +

Exception: Unable to resolve all CloudFormation resources after traversing dependency tree (maximum depth 40): []
```

I find a lot of these errors in the localstack docker output: `Error running stack deployment loop: An error occurred (ResourceConflictException) when calling the CreateFunction operation: Function already exist:`
