### ISSUE TITLE
Cannot resolve variable `${cf:}`

### ISSUE THREAD

**Issue by zoiman** [localstack/serverless-localstack#218] opened 2023-04-26 15:23 UTC
When I try to reference variables from the cloudformation stack like this:

```
   iam:
     role:
       statements:
         - Effect: 'Allow'
           Action:
             - 'dynamodb:*'
           Resource:
             - ${cf:${self:custom.infrastructureStack}.TableArn}`
```

I receive the following error when deploying to localstack:
` - Cannot resolve variable at "provider.iam.role.statements.0.Resource.0": Value not found at "cf" source,`

The serverless containing this resource was successfully deployed before to localstack.

Deploying to AWS works.

**Comment by steffyP** [comment] 2023-05-17 07:50
Hi @zoiman,
we recently discovered that the localstack-serverless plugin behaves different when using serverless v2 vs v3. 
Could you check if this could be the case for you?

We also recently released localstack-serverless `1.1.0` which should fix the environment variable resolving when using serverless v3.

**Comment by zjawol** [comment] 2023-09-01 14:26
Hi @steffyP

I just encountered this issue on my project and found this chat. 

My packages:
"serverless-localstack": "^1.1.1",
"serverless": "^3.34.0",
"@aws-sdk/....": "^3.395.0",

It looks like there is an issue as I am getting the same error : Value not found at "cf" source

**Comment by steffyP** [comment] 2023-09-07 15:58
Hi @zjawol,

Could you please provide some more details? Ideally a reproducible sample 🙏 

Which resource are you using? It's possible that the cloudformation model in LocalStack does not yet support the output you are trying to access.

**Comment by steffyP** [comment] 2023-12-15 10:49
This issue seems to be stale. As we didn't get any response in three months, we are closing this issue now. Please feel free to reopen if it still persists, and provide updates logs and details.

**Closed by steffyP** 2023-12-15 10:49 UTC
Labels: status: response required
