### ISSUE TITLE
Incorrect Account ID for Lambda on deploy

### ISSUE THREAD

**Issue by nosovj** [localstack/serverless-localstack#38] opened 2019-08-25 04:23 UTC
When deploying Serverless to LocalStack with the command `serverless deploy --stage local --verbose` and then check the docker logs by doing `docker logs -f <CONTAINER ID>`, it shows up that the Lambda account id (123456789012) is different than the service account ids (000000000000).

I also get the following warning: `2019-08-25T03:14:13:WARNING:localstack.services.awslambda.lambda_api: Function not found: arn:aws:lambda:us-east-1:000000000000:function:<LAMBDA NAME>`, this is due to the fact that the account id is different. 

I have a feeling that the issue could by fixed by either changing the the account id to match. I found https://github.com/localstack/localstack/issues/62, which indicates that this has been fixed in the past on the LocalStack side. It also looks like LocalStack explicitly sets 000000000000 as the account id, but there is no way to change it. https://github.com/localstack/localstack/blob/master/localstack/constants.py#L44-L45

I'm not sure if this is an issue on the serverless or localstack stide.

**Comment by kshahzada** [comment] 2019-10-24 17:03
Hi All,

Getting the same issue here. I'd be willing to try and fix it if someone can give me a bit of guidance on what is going on. If we think it's because it's not parsing the user's id correctly, I found the parser in aws_stack.py. I tried setting my local ACCESS_KEY_ID to '000000000000' as a hail-mary... didn't work.

I also can confirm that the serverless.yml file works fine in AWS deployment.


My logs:
```localstack_demo | 2019-10-24 16:48:35,348:API: 127.0.0.1 - - [24/Oct/2019 16:48:35] "GET /myService-dev-ServerlessDeploymentBucket-I6PLCGOGW52A?location HTTP/1.1" 404 -
localstack_demo | 2019-10-24 16:48:35,372:API: 127.0.0.1 - - [24/Oct/2019 16:48:35] "PUT /myService-dev-ServerlessDeploymentBucket-I6PLCGOGW52A HTTP/1.1" 200 -
localstack_demo | 2019-10-24T16:48:35:DEBUG:localstack.services.cloudformation.cloudformation_listener: Error response from CloudFormation (400) POST /: b'<ErrorResponse xmlns="http://cloudformation.amazonaws.com/doc/2010-05-15/">\n  <Error>\n    <Type>Sender</Type>\n    <Code>ValidationError</Code>\n    <Message>Stack with id myService-dev does not exist</Message>\n  </Error>\n  <RequestId>cf4c737e-5ae2-11e4-a7c9-ad44eEXAMPLE</RequestId>\n</ErrorResponse>'
localstack_demo | 2019-10-24T16:48:35:DEBUG:localstack.services.cloudformation.cloudformation_starter: Currently updating stack resource myService-dev/ServerlessDeploymentBucket: None
localstack_demo | 2019-10-24T16:48:35:DEBUG:localstack.services.cloudformation.cloudformation_starter: Deploying CloudFormation resource (update=False): {'Type': 'AWS::S3::Bucket', 'Properties': {'BucketEncryption': {'ServerSideEncryptionConfiguration': [{'ServerSideEncryptionByDefault': {'SSEAlgorithm': 'AES256'}}]}, 'BucketName': 'myService-dev-ServerlessDeploymentBucket-I6PLCGOGW52A'}}
localstack_demo | 2019-10-24T16:48:35:DEBUG:localstack.utils.cloudformation.template_deployer: Deploying resource type "S3::Bucket" id "ServerlessDeploymentBucket"
localstack_demo | 2019-10-24T16:48:35:DEBUG:localstack.utils.cloudformation.template_deployer: Request for creating resource type "S3::Bucket": create_bucket {'Bucket': 'myService-dev-ServerlessDeploymentBucket-I6PLCGOGW52A', 'ACL': 'public-read', 'CreateBucketConfiguration': {'LocationConstraint': 'us-east-1'}}
localstack_demo | 2019-10-24 16:48:40,480:API: 127.0.0.1 - - [24/Oct/2019 16:48:40] "GET /myService-dev-ServerlessDeploymentBucket-I6PLCGOGW52A?list-type=2&prefix=serverless%2FmyService%2Fdev HTTP/1.1" 200 -
localstack_demo | 2019-10-24T16:48:40:WARNING:localstack.services.awslambda.lambda_api: Function not found: arn:aws:lambda:us-east-1:000000000000:function:myService-dev-upload
localstack_demo | 2019-10-24 16:59:27,922:API: 127.0.0.1 - - [24/Oct/2019 16:59:27] "GET /myService-dev-ServerlessDeploymentBucket-I6PLCGOGW52A?list-type=2&prefix=serverless%2FmyService%2Fdev HTTP/1.1" 200 -
localstack_demo | 2019-10-24T16:59:27:WARNING:localstack.services.awslambda.lambda_api: Function not found: arn:aws:lambda:us-east-1:000000000000:function:myService-dev-upload
```

Thanks

**Comment by kshahzada** [comment] 2019-10-24 17:28
@whummer if you have any ideas I'll look into it

**Comment by pjmeisch-cc** [comment] 2019-10-30 13:36
same problem here. This seems to prevent s3 to lambda notifications to be working, because the notification should be bound to the lambda with "000000000000", but that does not exists, as the lambda's arn has "12345678912", so the notification configuration is not added to the bucket

**Comment by whummer** [comment] 2019-11-14 22:05
Thanks for reporting @nosovj @kshahzada @pjmeisch-cc . This appears to be an issue on LocalStack side, not with this Serverless plugin.

Can you please provide a small sample to reproduce this issue? Thanks!

**Comment by whummer** [comment] 2020-01-02 11:15
Any updates on this @nosovj @kshahzada @pjmeisch-cc ? If you could provide a small, self-contained example (ideally a small Github project with code+config), that would make it so much easier to look into this, and reduce turnaround time. Thanks!

**Comment by amar02041988** [comment] 2020-03-23 12:08
I am also facing this issue now. Guys any updates on this?

**Comment by whummer** [comment] 2020-03-31 00:17
Thanks for the update @amar02041988 - can you please provide a small, isolated example to reproduce this issue? Thanks

**Comment by sirjoe** [comment] 2020-04-06 01:27
Hi @whummer , I just experienced the same issue. Please find the code below.

**serverless.yml**
```
service: sca

plugins:
  - serverless-localstack
  - serverless-deployment-bucket
custom:
  localstack:
    stages:
      - local
    host: http://localhost
    autostart: false

provider:
  name: aws
  runtime: nodejs8.10
  region: us-east-1
  stage: local
  deploymentBucket:
    name: ${self:service}-${opt:stage}-deployment-bucket

# define endpoints
functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          cors: true
          method: get
          integration: mock
          request:
            template:
              application/json: '{"statusCode": 200}'
          response:
            template: $input.path('$')
            statusCodes:
              200:
                pattern: ""
```

**Localstack log**
```
localstack_1  | 2020-04-06T01:22:41:DEBUG:localstack.services.cloudformation.cloudformation_listener: Error response for CloudFormation action "DescribeStacks" (400) POST /: b'<ErrorResponse xmlns="http://cloudformation.amazonaws.com/doc/2010-05-15/">\n  <Error>\n    <Type>Sender</Type>\n    <Code>ValidationError</Code>\n    <Message>Stack with id sca-local does not exist</Message>\n  </Error>\n  <RequestId>cf4c737e-5ae2-11e4-a7c9-ad44eEXAMPLE</RequestId>\n</ErrorResponse>'
localstack_1  | 2020-04-06T01:22:41:WARNING:localstack.services.awslambda.lambda_api: Function not found: arn:aws:lambda:us-east-1:000000000000:function:sca-local-hello
localstack_1  | 2020-04-06T01:22:41:DEBUG:localstack.services.cloudformation.cloudformation_listener: Download CloudFormation template content from local S3: sca-local-deployment-bucket - serverless/sca/local/1586136161742-2020-04-06T01:22:41.742Z/compiled-cloudformation-template.json
localstack_1  | 2020-04-06T01:22:41:DEBUG:localstack.services.cloudformation.cloudformation_listener: Download CloudFormation template content from local S3: sca-local-deployment-bucket - serverless/sca/local/1586136161742-2020-04-06T01:22:41.742Z/compiled-cloudformation-template.json
localstack_1  | 2020-04-06T01:22:42:DEBUG:localstack.services.cloudformation.cloudformation_starter: Currently processing stack resource sca-local/HelloLogGroup: None
localstack_1  | 2020-04-06T01:22:42:DEBUG:localstack.services.cloudformation.cloudformation_starter: Deploying CloudFormation resource (update=False, exists=False, updateable=False): {'Type': 'AWS::Logs::LogGroup', 'Properties': {'LogGroupName': '/aws/lambda/sca-local-hello'}}
localstack_1  | 2020-04-06T01:22:42:DEBUG:localstack.utils.cloudformation.template_deployer: Running action "create" for resource type "Logs::LogGroup" id "HelloLogGroup"
localstack_1  | 2020-04-06T01:22:42:DEBUG:localstack.utils.cloudformation.template_deployer: Request for resource type "Logs::LogGroup" in region us-east-1: create_log_group {'logGroupName': '/aws/lambda/sca-local-hello'}
localstack_1  | 2020-04-06T01:22:42:DEBUG:localstack.services.cloudformation.cloudformation_starter: Currently processing stack resource sca-local/IamRoleLambdaExecution: None
localstack_1  | 2020-04-06T01:22:42:DEBUG:localstack.services.cloudformation.cloudformation_starter: Resource IamRoleLambdaExecution need not be deployed (is_updateable=False): {'Type': 'AWS::IAM::Role', 'Properties': {'AssumeRolePolicyDocument': {'Version': '2012-10-17', 'Statement': [{'Effect': 'Allow', 'Principal': {'Service': ['lambda.amazonaws.com']}, 'Action': ['sts:AssumeRole']}]}, 'Policies': [{'PolicyName': 'sca-local-lambda', 'PolicyDocument': {'Version': '2012-10-17', 'Statement': [{'Effect': 'Allow', 'Action': ['logs:CreateLogStream', 'logs:CreateLogGroup'], 'Resource': ['arn:aws:logs:us-east-1:123456789012:log-group:/aws/lambda/sca-local*:*']}, {'Effect': 'Allow', 'Action': ['logs:PutLogEvents'], 'Resource': ['arn:aws:logs:us-east-1:123456789012:log-group:/aws/lambda/sca-local*:*:*']}]}}], 'Path': '/', 'RoleName': 'sca-local-us-east-1-lambdaRole'}} True
localstack_1  | 2020-04-06T01:22:42:DEBUG:localstack.services.cloudformation.cloudformation_starter: Currently processing stack resource sca-local/HelloLambdaFunction: None
localstack_1  | 2020-04-06T01:22:42:WARNING:localstack.services.awslambda.lambda_api: Function not found: arn:aws:lambda:us-east-1:000000000000:function:sca-local-hello
localstack_1  | 2020-04-06T01:22:42:WARNING:localstack.services.awslambda.lambda_api: Function not found: arn:aws:lambda:us-east-1:000000000000:function:sca-local-hello
localstack_1  | 2020-04-06T01:22:42:INFO:localstack.services.cloudformation.cloudformation_starter: Resource HelloLambdaFunction cannot be deployed, found unsatisfied dependencies. {'Type': 'AWS::Lambda::Function', 'Properties': {'Code': {'S3Bucket': 'sca-local-deployment-bucket', 'S3Key': 'serverless/sca/local/1586136161742-2020-04-06T01:22:41.742Z/sca.zip'}, 'FunctionName': 'sca-local-hello', 'Handler': 'handler.hello', 'MemorySize': 1024, 'Role': 'arn:aws:iam::123456789012:role/sca-local-us-east-1-lambdaRole', 'Runtime': 'nodejs8.10', 'Timeout': 6}, 'DependsOn': ['HelloLogGroup', 'IamRoleLambdaExecution']}
localstack_1  | 2020-04-06T01:22:42:DEBUG:localstack.services.cloudformation.cloudformation_starter: Currently processing stack resource sca-local/HelloLambdaVersionuG6HRmMp1g4JWf4K63kWfmWBLMsLPbWay1RrgrzIgVc: None
localstack_1  | 2020-04-06T01:22:42:WARNING:localstack.services.awslambda.lambda_api: Function not found: arn:aws:lambda:us-east-1:000000000000:function:sca-local-hello
localstack_1  | 2020-04-06T01:22:42:DEBUG:localstack.services.cloudformation.cloudformation_starter: Deploying CloudFormation resource (update=False, exists=False, updateable=False): {'Type': 'AWS::Lambda::Version', 'DeletionPolicy': 'Retain', 'Properties': {'FunctionName': 'sca-local-hello', 'CodeSha256': 'WzYpk7/zorw1CtoRE9gyTcoDZq8hyZOgOeLhhErWzFI='}}
localstack_1  | 2020-04-06T01:22:42:DEBUG:localstack.utils.cloudformation.template_deployer: Running action "create" for resource type "Lambda::Version" id "HelloLambdaVersionuG6HRmMp1g4JWf4K63kWfmWBLMsLPbWay1RrgrzIgVc"
localstack_1  | 2020-04-06T01:22:42:DEBUG:localstack.utils.cloudformation.template_deployer: Request for resource type "Lambda::Version" in region us-east-1: publish_version {'FunctionName': 'sca-local-hello', 'CodeSha256': 'WzYpk7/zorw1CtoRE9gyTcoDZq8hyZOgOeLhhErWzFI='}
localstack_1  | 2020-04-06T01:22:42:WARNING:localstack.services.awslambda.lambda_api: Function not found: arn:aws:lambda:us-east-1:000000000000:function:sca-local-hello
localstack_1  | 2020-04-06T01:22:42:WARNING:localstack.utils.cloudformation.template_deployer: Error calling <bound method ClientCreator._create_api_method.<locals>._api_call of <botocore.client.Lambda object at 0x7feb8709e0d0>> with params: {'FunctionName': 'sca-local-hello', 'CodeSha256': 'WzYpk7/zorw1CtoRE9gyTcoDZq8hyZOgOeLhhErWzFI='} for resource: {'Type': 'AWS::Lambda::Version', 'DeletionPolicy': 'Retain', 'Properties': {'FunctionName': 'sca-local-hello', 'CodeSha256': 'WzYpk7/zorw1CtoRE9gyTcoDZq8hyZOgOeLhhErWzFI='}}
```
You can see the issue mentioned by @pjmeisch-cc. Is there a way to specify accountId in localstack? Thanks for your help in advance.

**Comment by pradeepgnd** [comment] 2020-04-15 18:36
Facing same issue, is there any update?

**Comment by whummer** [comment] 2020-07-29 20:47
Thanks for the update @sirjoe @pradeepgnd . This appears to be fixed in the `latest` version of LocalStack.

Serverless config:
```
$ cat serverless.yml 
service: sca

plugins:
  - serverless-localstack
  - serverless-deployment-bucket
custom:
  localstack:
    stages:
      - local
    host: http://localhost
    autostart: false

provider:
  name: aws
  runtime: nodejs8.10
  region: us-east-1
  stage: local
  deploymentBucket:
    name: ${self:service}-${opt:stage}-deployment-bucket

# define endpoints
functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          cors: true
          method: get
          integration: mock
          request:
            template:
              application/json: '{"statusCode": 200}'
          response:
            template: $input.path('$')
            statusCodes:
              200:
                pattern: ""
```

Deployment succeeds:
```
$ sls deploy --stage local
...
Serverless: Stack create finished...
...
...
```

Account IDs seem to be correct:
```
$ awslocal lambda list-functions | grep arn:
            "FunctionArn": "arn:aws:lambda:us-east-1:000000000000:function:sca-foo-local-hello",
            "Role": "arn:aws:iam::000000000000:role/sca-foo-local-us-east-1-lambdaRole",
```

Please report here if this problem persists - thanks for your help!

**Closed by whummer** 2020-07-29 20:47 UTC
Labels: bug, needs-triaging
